Para obtener un mejor resultado en la integracion es mejor utilizar aproximaciones de segundo orden y con varias variables. Como vimos en clase:
$$
\vec y_{n+1} = \vec y_n + h \vec f + \frac{1}{2}h^2 \left(\frac{\partial \vec f}{\partial x} +\mathbb{j}\vec f\right)
$$

In [36]:
from pylab import *
%matplotlib inline

In [37]:
def integra2(ec,d_ec,p_ini,x,h=0.1):
    tiempos = arange(x[0],x[1]+h,h)
    sol = zeros((len(tiempos),len(p_ini)))
    sol[0,:] = p_ini  
    for i in xrange(len(tiempos)-1):
        f = ec(sol[i,:],tiempos[i])
        df,jac = d_ec(sol[i,:],tiempos[i])
        sol[i+1,:] = sol[i,:]+h*f+(0.5*h*h*(df+dot(jac,f)))
    return tiempos,sol

def prueba(y,t):
    return array([y[1]-y[0]])

def d_prueba(y,t):
    return array([0,0]),array([[0,1],[-1,0]])

t,y=integra2(prueba,d_prueba,[1,0],[0,50],0.1)
#plot(y[:,0],y[:,1])
plot(t,y[:,0],t,cos(t))
    
    
    

ValueError: shapes (2,2) and (1,) not aligned: 2 (dim 1) != 1 (dim 0)

In [38]:
def p(y,t):
    return array([y[1],-2*y[1]-0.5*sin(y[0])+cos(-t)])
def dp(y,t):
    return array([0,-exp(-t)]),array([[0,1,[-0.5*cos(y[0]),-2]]])
t,y=integra2(p,dp,[1,0],[0,100],0.01)
plot(y[:,0],y[:,1])

ValueError: setting an array element with a sequence.

In [39]:
def rk2(ec,p_ini,x,h=0.1):
    tiempos = arange(x[0],x[1]+h,h)
    sol = zeros((len(tiempos),len(p_ini)))
    sol[0,:] = p_ini
    for i in xrange(len(tiempos)-1):
        k= h*ec(sol[1,:],tiempos[i])
        f = ec(sol[i,:]+0.5*k,tiempos[i]+0.5*h)
        sol[i+1,:]=sol[i,:]+h*f
    return tiempos,sol    



In [40]:
t,y=integra2(p,dp,[1,0],[0,100],0.01)
plot(y[:,0],y[:,1])

ValueError: setting an array element with a sequence.

In [34]:
x = zeros((2,6))
print x
x[1,1]=3
x[0,1]=0
print x
print x[:,1]
print x[1,:]


[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  3.  0.  0.  0.  0.]]
[ 0.  3.]
[ 0.  3.  0.  0.  0.  0.]


In [35]:
a=array([2,6])
b=[2,6]
print a,b
print 2*a,2*b


[2 6] [2, 6]
[ 4 12] [2, 6, 2, 6]


In [9]:
A = array ([[1,0],[0,1]])
B = matrix([[1,0],[0,1]])
print A
print B
print A*b
print dot(B,b), dot(B,b)

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
[[2 0]
 [0 6]]
[[2 6]] [[2 6]]


In [11]:
A = array([[1,2],[3,4]])
a = array([6,7])
print A[0,0],A[0,1],A[1,0],A[1,1]
print A*a

1 2 3 4
[[ 6 14]
 [18 28]]


In [12]:
print dot(A,a)

[20 46]
